import os
import json
import math
import base64
import traceback
import subprocess
import sys
from flask import Flask, request, jsonify, Response
from flask_cors import CORS
 
app = Flask(__name__)
CORS(app)
 
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
MAX_PAGES_PER_CHUNK = 80
MAX_FILE_BYTES = 900 * 1024 * 1024
app.config["MAX_CONTENT_LENGTH"] = MAX_FILE_BYTES
 
_HTML_B64 = "PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CjxtZXRhIGNoYXJzZXQ9IlVURi04Ij4KPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjAiPgo8dGl0bGU+QXBwZWFsIFJlY29yZCBTdW1tYXJ5PC90aXRsZT4KPGxpbmsgaHJlZj0iaHR0cHM6Ly9mb250cy5nb29nbGVhcGlzLmNvbS9jc3MyP2ZhbWlseT1QbGF5ZmFpcitEaXNwbGF5Oml0YWwsd2dodEAwLDQwMDswLDYwMDswLDcwMDsxLDQwMCZmYW1pbHk9Q3JpbXNvbitQcm86aXRhbCx3Z2h0QDAsMzAwOzAsNDAwOzAsNTAwOzEsMzAwOzEsNDAwJmZhbWlseT1ETStNb25vOndnaHRAMzAwOzQwMCZkaXNwbGF5PXN3YXAiIHJlbD0ic3R5bGVzaGVldCI+CjxzdHlsZT4KICA6cm9vdCB7CiAgICAtLW5hdnk6ICMwZDFiMmE7IC0tbmF2eS1taWQ6ICMxNjIwMzI7CiAgICAtLWdvbGQ6ICNjOWE4NGM7IC0tZ29sZC1saWdodDogI2UyYzQ3YTsgLS1jcmVhbTogI2ZhZjZlZjsKICAgIC0tdGV4dC1saWdodDogIzdhNmE1MDsgLS1ib3JkZXItZ29sZDogcmdiYSgyMDEsMTY4LDc2LDAuMyk7CiAgfQogICogeyBib3gtc2l6aW5nOiBib3JkZXItYm94OyBtYXJnaW46IDA7IHBhZGRpbmc6IDA7IH0KICBib2R5IHsgZm9udC1mYW1pbHk6ICdDcmltc29uIFBybycsIEdlb3JnaWEsIHNlcmlmOyBiYWNrZ3JvdW5kOiB2YXIoLS1uYXZ5KTsgY29sb3I6IHZhcigtLWNyZWFtKTsgbWluLWhlaWdodDogMTAwdmg7IH0KICBib2R5OjpiZWZvcmUgeyBjb250ZW50OiAnJzsgcG9zaXRpb246IGZpeGVkOyBpbnNldDogMDsgYmFja2dyb3VuZC1pbWFnZTogcmFkaWFsLWdyYWRpZW50KGVsbGlwc2UgYXQgMjAlIDAlLCByZ2JhKDIwMSwxNjgsNzYsMC4wOCkgMCUsIHRyYW5zcGFyZW50IDUwJSksIHJhZGlhbC1ncmFkaWVudChlbGxpcHNlIGF0IDgwJSAxMDAlLCByZ2JhKDIwMSwxNjgsNzYsMC4wNikgMCUsIHRyYW5zcGFyZW50IDUwJSk7IHBvaW50ZXItZXZlbnRzOiBub25lOyB6LWluZGV4OiAwOyB9CiAgLndyYXBwZXIgeyBwb3NpdGlvbjogcmVsYXRpdmU7IHotaW5kZXg6IDE7IG1heC13aWR0aDogMTEwMHB4OyBtYXJnaW46IDAgYXV0bzsgcGFkZGluZzogMCAyNHB4IDgwcHg7IH0KCiAgaGVhZGVyIHsgdGV4dC1hbGlnbjogY2VudGVyOyBwYWRkaW5nOiA1NnB4IDAgNDBweDsgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkIHZhcigtLWJvcmRlci1nb2xkKTsgbWFyZ2luLWJvdHRvbTogNDhweDsgfQogIC5zZWFsIHsgd2lkdGg6IDY0cHg7IGhlaWdodDogNjRweDsgbWFyZ2luOiAwIGF1dG8gMjBweDsgYm9yZGVyOiAycHggc29saWQgdmFyKC0tZ29sZCk7IGJvcmRlci1yYWRpdXM6IDUwJTsgZGlzcGxheTogZmxleDsgYWxpZ24taXRlbXM6IGNlbnRlcjsganVzdGlmeS1jb250ZW50OiBjZW50ZXI7IGZvbnQtc2l6ZTogMjhweDsgY29sb3I6IHZhcigtLWdvbGQpOyBwb3NpdGlvbjogcmVsYXRpdmU7IH0KICAuc2VhbDo6YmVmb3JlIHsgY29udGVudDogJyc7IHBvc2l0aW9uOiBhYnNvbHV0ZTsgaW5zZXQ6IDRweDsgYm9yZGVyOiAxcHggc29saWQgdmFyKC0tYm9yZGVyLWdvbGQpOyBib3JkZXItcmFkaXVzOiA1MCU7IH0KICBoMSB7IGZvbnQtZmFtaWx5OiAnUGxheWZhaXIgRGlzcGxheScsIHNlcmlmOyBmb250LXNpemU6IGNsYW1wKDJyZW0sNHZ3LDNyZW0pOyBmb250LXdlaWdodDogNzAwOyBjb2xvcjogdmFyKC0tZ29sZC1saWdodCk7IGxldHRlci1zcGFjaW5nOiAwLjAyZW07IGxpbmUtaGVpZ2h0OiAxLjE7IH0KICAuc3VidGl0bGUgeyBtYXJnaW4tdG9wOiAxMHB4OyBmb250LXNpemU6IDEuMDVyZW07IGNvbG9yOiByZ2JhKDIwMSwxNjgsNzYsMC42KTsgZm9udC1zdHlsZTogaXRhbGljOyBsZXR0ZXItc3BhY2luZzogMC4wOGVtOyB9CgogIC51cGxvYWQtc2VjdGlvbiB7IGJhY2tncm91bmQ6IHZhcigtLW5hdnktbWlkKTsgYm9yZGVyOiAxcHggc29saWQgdmFyKC0tYm9yZGVyLWdvbGQpOyBib3JkZXItcmFkaXVzOiA0cHg7IHBhZGRpbmc6IDQ4cHggNDBweDsgdGV4dC1hbGlnbjogY2VudGVyOyBtYXJnaW4tYm90dG9tOiAzMnB4OyB9CiAgLnBpY2stYXJlYSB7IGJvcmRlcjogMnB4IGRhc2hlZCByZ2JhKDIwMSwxNjgsNzYsMC40KTsgYm9yZGVyLXJhZGl1czogNHB4OyBwYWRkaW5nOiA1MnB4IDMycHg7IGJhY2tncm91bmQ6IHJnYmEoMjAxLDE2OCw3NiwwLjAzKTsgdHJhbnNpdGlvbjogYWxsIDAuMjVzOyB9CiAgLnBpY2stYXJlYS5oYXMtZmlsZSB7IGJvcmRlci1jb2xvcjogdmFyKC0tZ29sZCk7IGJhY2tncm91bmQ6IHJnYmEoMjAxLDE2OCw3NiwwLjA3KTsgfQogIC5kcm9wLWljb24geyBmb250LXNpemU6IDIuOHJlbTsgbWFyZ2luLWJvdHRvbTogMTZweDsgZGlzcGxheTogYmxvY2s7IG9wYWNpdHk6IDAuNzsgfQogIC5waWNrLWFyZWEgaDMgeyBmb250LWZhbWlseTogJ1BsYXlmYWlyIERpc3BsYXknLCBzZXJpZjsgZm9udC1zaXplOiAxLjNyZW07IGNvbG9yOiB2YXIoLS1nb2xkLWxpZ2h0KTsgbWFyZ2luLWJvdHRvbTogOHB4OyB9CiAgLnBpY2stYXJlYSBwIHsgY29sb3I6IHJnYmEoMjUwLDI0NiwyMzksMC41KTsgZm9udC1zaXplOiAwLjk1cmVtOyBtYXJnaW4tYm90dG9tOiAyMHB4OyB9CiAgI2ZpbGVJbnB1dCB7IGRpc3BsYXk6IG5vbmU7IH0KICAuYnRuLWJyb3dzZSB7IGRpc3BsYXk6IGlubGluZS1ibG9jazsgYm9yZGVyOiAxcHggc29saWQgdmFyKC0tZ29sZCk7IGNvbG9yOiB2YXIoLS1nb2xkKTsgYmFja2dyb3VuZDogdHJhbnNwYXJlbnQ7IHBhZGRpbmc6IDEwcHggMjhweDsgZm9udC1mYW1pbHk6ICdDcmltc29uIFBybycsIHNlcmlmOyBmb250LXNpemU6IDFyZW07IGJvcmRlci1yYWRpdXM6IDNweDsgY3Vyc29yOiBwb2ludGVyOyB0cmFuc2l0aW9uOiBhbGwgMC4yczsgfQogIC5idG4tYnJvd3NlOmhvdmVyIHsgYmFja2dyb3VuZDogcmdiYSgyMDEsMTY4LDc2LDAuMTIpOyB9CiAgLmZpbGUtaW5mbyB7IG1hcmdpbi10b3A6IDE4cHg7IGRpc3BsYXk6IG5vbmU7IGFsaWduLWl0ZW1zOiBjZW50ZXI7IGp1c3RpZnktY29udGVudDogY2VudGVyOyBnYXA6IDEwcHg7IGZvbnQtc2l6ZTogMC45NXJlbTsgfQogIC5maWxlLWluZm8udmlzaWJsZSB7IGRpc3BsYXk6IGZsZXg7IH0KICAuZm5hbWUgeyBjb2xvcjogdmFyKC0tZ29sZC1saWdodCk7IGZvbnQtd2VpZ2h0OiA1MDA7IHdvcmQtYnJlYWs6IGJyZWFrLWFsbDsgfQogIC5mc2l6ZSB7IGNvbG9yOiB2YXIoLS10ZXh0LWxpZ2h0KTsgZm9udC1zaXplOiAwLjg1cmVtOyBmbGV4LXNocmluazogMDsgfQogIC5idG4tY2xlYXIgeyBiYWNrZ3JvdW5kOiBub25lOyBib3JkZXI6IG5vbmU7IGNvbG9yOiB2YXIoLS10ZXh0LWxpZ2h0KTsgY3Vyc29yOiBwb2ludGVyOyBmb250LXNpemU6IDEuMXJlbTsgcGFkZGluZzogMCA0cHg7IGZsZXgtc2hyaW5rOiAwOyB9CiAgLmJ0bi1jbGVhcjpob3ZlciB7IGNvbG9yOiAjZjRhMGEwOyB9CiAgLmJ0bi1hbmFseXplIHsgbWFyZ2luLXRvcDogMjhweDsgYmFja2dyb3VuZDogbGluZWFyLWdyYWRpZW50KDEzNWRlZywgdmFyKC0tZ29sZCkgMCUsICNhMDdjMzAgMTAwJSk7IGNvbG9yOiB2YXIoLS1uYXZ5KTsgYm9yZGVyOiBub25lOyBwYWRkaW5nOiAxNnB4IDUycHg7IGZvbnQtZmFtaWx5OiAnUGxheWZhaXIgRGlzcGxheScsIHNlcmlmOyBmb250LXNpemU6IDEuMDVyZW07IGZvbnQtd2VpZ2h0OiA2MDA7IGxldHRlci1zcGFjaW5nOiAwLjA1ZW07IGJvcmRlci1yYWRpdXM6IDNweDsgY3Vyc29yOiBwb2ludGVyOyB0cmFuc2l0aW9uOiBhbGwgMC4yczsgYm94LXNoYWRvdzogMCA0cHggMjBweCByZ2JhKDIwMSwxNjgsNzYsMC4zKTsgZGlzcGxheTogYmxvY2s7IG1hcmdpbi1sZWZ0OiBhdXRvOyBtYXJnaW4tcmlnaHQ6IGF1dG87IH0KICAuYnRuLWFuYWx5emU6aG92ZXI6bm90KDpkaXNhYmxlZCkgeyB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTJweCk7IGJveC1zaGFkb3c6IDAgOHB4IDI4cHggcmdiYSgyMDEsMTY4LDc2LDAuNCk7IH0KICAuYnRuLWFuYWx5emU6ZGlzYWJsZWQgeyBvcGFjaXR5OiAwLjQ1OyBjdXJzb3I6IG5vdC1hbGxvd2VkOyB9CgogIC5wcm9ncmVzcy1zZWN0aW9uIHsgZGlzcGxheTogbm9uZTsgYmFja2dyb3VuZDogdmFyKC0tbmF2eS1taWQpOyBib3JkZXI6IDFweCBzb2xpZCB2YXIoLS1ib3JkZXItZ29sZCk7IGJvcmRlci1yYWRpdXM6IDRweDsgcGFkZGluZzogNDBweDsgdGV4dC1hbGlnbjogY2VudGVyOyBtYXJnaW4tYm90dG9tOiAzMnB4OyB9CiAgLnByb2dyZXNzLXNlY3Rpb24udmlzaWJsZSB7IGRpc3BsYXk6IGJsb2NrOyB9CiAgLnNwaW5uZXIgeyB3aWR0aDogNTJweDsgaGVpZ2h0OiA1MnB4OyBib3JkZXI6IDNweCBzb2xpZCByZ2JhKDIwMSwxNjgsNzYsMC4yKTsgYm9yZGVyLXRvcC1jb2xvcjogdmFyKC0tZ29sZCk7IGJvcmRlci1yYWRpdXM6IDUwJTsgYW5pbWF0aW9uOiBzcGluIDAuOHMgbGluZWFyIGluZmluaXRlOyBtYXJnaW46IDAgYXV0byAyNHB4OyB9CiAgQGtleWZyYW1lcyBzcGluIHsgdG8geyB0cmFuc2Zvcm06IHJvdGF0ZSgzNjBkZWcpOyB9IH0KICAucHJvZ3Jlc3MtbGFiZWwgeyBmb250LWZhbWlseTogJ1BsYXlmYWlyIERpc3BsYXknLCBzZXJpZjsgZm9udC1zaXplOiAxLjE1cmVtOyBjb2xvcjogdmFyKC0tZ29sZC1saWdodCk7IG1hcmdpbi1ib3R0b206IDhweDsgfQogIC5wcm9ncmVzcy1zdWIgeyBmb250LXNpemU6IDAuOXJlbTsgY29sb3I6IHJnYmEoMjUwLDI0NiwyMzksMC40NSk7IGZvbnQtc3R5bGU6IGl0YWxpYzsgfQogIC5wcm9ncmVzcy1iYXItd3JhcCB7IG1hcmdpbi10b3A6IDIwcHg7IGJhY2tncm91bmQ6IHJnYmEoMjAxLDE2OCw3NiwwLjEpOyBib3JkZXI6IDFweCBzb2xpZCB2YXIoLS1ib3JkZXItZ29sZCk7IGJvcmRlci1yYWRpdXM6IDNweDsgaGVpZ2h0OiA4cHg7IG92ZXJmbG93OiBoaWRkZW47IH0KICAucHJvZ3Jlc3MtYmFyLWZpbGwgeyBoZWlnaHQ6IDEwMCU7IGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCg5MGRlZywgdmFyKC0tZ29sZCksIHZhcigtLWdvbGQtbGlnaHQpKTsgd2lkdGg6IDAlOyB0cmFuc2l0aW9uOiB3aWR0aCAwLjVzIGVhc2U7IGJvcmRlci1yYWRpdXM6IDNweDsgfQoKICAuZXJyb3ItYm94IHsgZGlzcGxheTogbm9uZTsgYmFja2dyb3VuZDogcmdiYSgxMzksMzIsMzIsMC4xNSk7IGJvcmRlcjogMXB4IHNvbGlkIHJnYmEoMTM5LDMyLDMyLDAuNSk7IGJvcmRlci1yYWRpdXM6IDRweDsgcGFkZGluZzogMjBweCAyNHB4OyBtYXJnaW4tYm90dG9tOiAzMnB4OyBjb2xvcjogI2Y0YTBhMDsgZm9udC1zaXplOiAwLjk1cmVtOyBsaW5lLWhlaWdodDogMS42OyB9CiAgLmVycm9yLWJveC52aXNpYmxlIHsgZGlzcGxheTogYmxvY2s7IH0KCiAgI3Jlc3VsdHMgeyBkaXNwbGF5OiBub25lOyB9CiAgI3Jlc3VsdHMudmlzaWJsZSB7IGRpc3BsYXk6IGJsb2NrOyB9CiAgLnJlc3VsdHMtaGVhZGVyIHsgZGlzcGxheTogZmxleDsgYWxpZ24taXRlbXM6IGNlbnRlcjsganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuOyBtYXJnaW4tYm90dG9tOiA0MHB4OyBwYWRkaW5nLWJvdHRvbTogMjBweDsgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkIHZhcigtLWJvcmRlci1nb2xkKTsgZmxleC13cmFwOiB3cmFwOyBnYXA6IDE2cHg7IH0KICAucmVzdWx0cy1oZWFkZXIgaDIgeyBmb250LWZhbWlseTogJ1BsYXlmYWlyIERpc3BsYXknLCBzZXJpZjsgZm9udC1zaXplOiAxLjZyZW07IGNvbG9yOiB2YXIoLS1nb2xkLWxpZ2h0KTsgfQogIC5idG4tcmVzZXQgeyBiYWNrZ3JvdW5kOiB0cmFuc3BhcmVudDsgYm9yZGVyOiAxcHggc29saWQgdmFyKC0tYm9yZGVyLWdvbGQpOyBjb2xvcjogdmFyKC0tZ29sZCk7IHBhZGRpbmc6IDEwcHggMjRweDsgZm9udC1mYW1pbHk6ICdDcmltc29uIFBybycsIHNlcmlmOyBmb250LXNpemU6IDAuOTVyZW07IGJvcmRlci1yYWRpdXM6IDNweDsgY3Vyc29yOiBwb2ludGVyOyB0cmFuc2l0aW9uOiBhbGwgMC4yczsgfQogIC5idG4tcmVzZXQ6aG92ZXIgeyBiYWNrZ3JvdW5kOiByZ2JhKDIwMSwxNjgsNzYsMC4xKTsgYm9yZGVyLWNvbG9yOiB2YXIoLS1nb2xkKTsgfQoKICAuc2VjdGlvbi1jYXJkIHsgYmFja2dyb3VuZDogdmFyKC0tbmF2eS1taWQpOyBib3JkZXI6IDFweCBzb2xpZCB2YXIoLS1ib3JkZXItZ29sZCk7IGJvcmRlci1yYWRpdXM6IDRweDsgbWFyZ2luLWJvdHRvbTogMjRweDsgb3ZlcmZsb3c6IGhpZGRlbjsgfQogIC5zZWN0aW9uLWhlYWRlciB7IGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCg5MGRlZywgcmdiYSgyMDEsMTY4LDc2LDAuMTIpIDAlLCB0cmFuc3BhcmVudCAxMDAlKTsgcGFkZGluZzogMjBweCAyOHB4OyBkaXNwbGF5OiBmbGV4OyBhbGlnbi1pdGVtczogY2VudGVyOyBnYXA6IDE2cHg7IGN1cnNvcjogcG9pbnRlcjsgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkIHZhcigtLWJvcmRlci1nb2xkKTsgdXNlci1zZWxlY3Q6IG5vbmU7IHRyYW5zaXRpb246IGJhY2tncm91bmQgMC4yczsgfQogIC5zZWN0aW9uLWhlYWRlcjpob3ZlciB7IGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCg5MGRlZywgcmdiYSgyMDEsMTY4LDc2LDAuMTgpIDAlLCB0cmFuc3BhcmVudCAxMDAlKTsgfQogIC5zZWN0aW9uLW51bSB7IHdpZHRoOiAzNnB4OyBoZWlnaHQ6IDM2cHg7IGJvcmRlcjogMXB4IHNvbGlkIHZhcigtLWdvbGQpOyBib3JkZXItcmFkaXVzOiA1MCU7IGRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXI7IGp1c3RpZnktY29udGVudDogY2VudGVyOyBmb250LWZhbWlseTogJ0RNIE1vbm8nLCBtb25vc3BhY2U7IGZvbnQtc2l6ZTogMC44cmVtOyBjb2xvcjogdmFyKC0tZ29sZCk7IGZsZXgtc2hyaW5rOiAwOyB9CiAgLnNlY3Rpb24tdGl0bGUgeyBmb250LWZhbWlseTogJ1BsYXlmYWlyIERpc3BsYXknLCBzZXJpZjsgZm9udC1zaXplOiAxLjFyZW07IGNvbG9yOiB2YXIoLS1nb2xkLWxpZ2h0KTsgZmxleDogMTsgfQogIC5zZWN0aW9uLXRvZ2dsZSB7IGNvbG9yOiB2YXIoLS1nb2xkKTsgZm9udC1zaXplOiAxLjFyZW07IHRyYW5zaXRpb246IHRyYW5zZm9ybSAwLjI1czsgfQogIC5zZWN0aW9uLWNhcmQuY29sbGFwc2VkIC5zZWN0aW9uLXRvZ2dsZSB7IHRyYW5zZm9ybTogcm90YXRlKC05MGRlZyk7IH0KICAuc2VjdGlvbi1ib2R5IHsgcGFkZGluZzogMjhweDsgZm9udC1zaXplOiAxcmVtOyBsaW5lLWhlaWdodDogMS43NTsgY29sb3I6IHJnYmEoMjUwLDI0NiwyMzksMC44NSk7IH0KICAuc2VjdGlvbi1jYXJkLmNvbGxhcHNlZCAuc2VjdGlvbi1ib2R5IHsgbWF4LWhlaWdodDogMDsgcGFkZGluZy10b3A6IDA7IHBhZGRpbmctYm90dG9tOiAwOyBvdmVyZmxvdzogaGlkZGVuOyB9CiAgLnNlY3Rpb24tYm9keSBoMyB7IGZvbnQtZmFtaWx5OiAnUGxheWZhaXIgRGlzcGxheScsIHNlcmlmOyBmb250LXNpemU6IDEuMDVyZW07IGNvbG9yOiB2YXIoLS1nb2xkKTsgbWFyZ2luOiAyMnB4IDAgOHB4OyBwYWRkaW5nLWJvdHRvbTogNHB4OyBib3JkZXItYm90dG9tOiAxcHggc29saWQgcmdiYSgyMDEsMTY4LDc2LDAuMik7IH0KICAuc2VjdGlvbi1ib2R5IGgzOmZpcnN0LWNoaWxkIHsgbWFyZ2luLXRvcDogMDsgfQogIC5zZWN0aW9uLWJvZHkgaDQgeyBmb250LWZhbWlseTogJ0NyaW1zb24gUHJvJywgc2VyaWY7IGZvbnQtc2l6ZTogMC45NXJlbTsgZm9udC13ZWlnaHQ6IDUwMDsgY29sb3I6IHZhcigtLWdvbGQtbGlnaHQpOyBtYXJnaW46IDE0cHggMCA0cHg7IHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7IGxldHRlci1zcGFjaW5nOiAwLjA2ZW07IH0KICAuc2VjdGlvbi1ib2R5IHAgeyBtYXJnaW4tYm90dG9tOiAxMHB4OyB9CiAgLnNlY3Rpb24tYm9keSB1bCwgLnNlY3Rpb24tYm9keSBvbCB7IHBhZGRpbmctbGVmdDogMjJweDsgbWFyZ2luLWJvdHRvbTogMTBweDsgfQogIC5zZWN0aW9uLWJvZHkgbGkgeyBtYXJnaW4tYm90dG9tOiA1cHg7IH0KICAuZGF0ZS10YWcgeyBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7IGJhY2tncm91bmQ6IHJnYmEoMjAxLDE2OCw3NiwwLjEyKTsgYm9yZGVyOiAxcHggc29saWQgcmdiYSgyMDEsMTY4LDc2LDAuMjUpOyBjb2xvcjogdmFyKC0tZ29sZCk7IGZvbnQtZmFtaWx5OiAnRE0gTW9ubycsIG1vbm9zcGFjZTsgZm9udC1zaXplOiAwLjc1cmVtOyBwYWRkaW5nOiAycHggOHB4OyBib3JkZXItcmFkaXVzOiAycHg7IG1hcmdpbi1yaWdodDogNnB4OyB2ZXJ0aWNhbC1hbGlnbjogbWlkZGxlOyB9CiAgLmRvYy1lbnRyeSB7IHBhZGRpbmc6IDE0cHggMDsgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkIHJnYmEoMjAxLDE2OCw3NiwwLjEpOyB9CiAgLmRvYy1lbnRyeTpsYXN0LWNoaWxkIHsgYm9yZGVyLWJvdHRvbTogbm9uZTsgfQogIC50YWctYWRtaXR0ZWQgeyBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7IGJhY2tncm91bmQ6IHJnYmEoMjYsNzcsNDYsMC4zKTsgYm9yZGVyOiAxcHggc29saWQgcmdiYSgyNiw3Nyw0NiwwLjYpOyBjb2xvcjogIzZmY2Y5NzsgZm9udC1zaXplOiAwLjcycmVtOyBwYWRkaW5nOiAycHggOHB4OyBib3JkZXItcmFkaXVzOiAycHg7IGZvbnQtZmFtaWx5OiAnRE0gTW9ubycsIG1vbm9zcGFjZTsgfQogIC50YWctZGVuaWVkIHsgZGlzcGxheTogaW5saW5lLWJsb2NrOyBiYWNrZ3JvdW5kOiByZ2JhKDEzOSwzMiwzMiwwLjMpOyBib3JkZXI6IDFweCBzb2xpZCByZ2JhKDEzOSwzMiwzMiwwLjYpOyBjb2xvcjogI2Y0YTBhMDsgZm9udC1zaXplOiAwLjcycmVtOyBwYWRkaW5nOiAycHggOHB4OyBib3JkZXItcmFkaXVzOiAycHg7IGZvbnQtZmFtaWx5OiAnRE0gTW9ubycsIG1vbm9zcGFjZTsgfQoKICBmb290ZXIgeyB0ZXh0LWFsaWduOiBjZW50ZXI7IHBhZGRpbmc6IDMycHggMCAwOyBib3JkZXItdG9wOiAxcHggc29saWQgdmFyKC0tYm9yZGVyLWdvbGQpOyBtYXJnaW4tdG9wOiA0OHB4OyBmb250LXNpemU6IDAuODVyZW07IGNvbG9yOiByZ2JhKDIwMSwxNjgsNzYsMC4zNSk7IGZvbnQtc3R5bGU6IGl0YWxpYzsgfQogIEBtZWRpYSAobWF4LXdpZHRoOiA2MDBweCkgeyAudXBsb2FkLXNlY3Rpb24sIC5zZWN0aW9uLWJvZHkgeyBwYWRkaW5nOiAyNHB4IDIwcHg7IH0gLnBpY2stYXJlYSB7IHBhZGRpbmc6IDM2cHggMjBweDsgfSAuYnRuLWFuYWx5emUgeyB3aWR0aDogMTAwJTsgfSB9Cjwvc3R5bGU+CjwvaGVhZD4KPGJvZHk+CjxkaXYgY2xhc3M9IndyYXBwZXIiPgogIDxoZWFkZXI+CiAgICA8ZGl2IGNsYXNzPSJzZWFsIj7impY8L2Rpdj4KICAgIDxoMT5BcHBlYWwgUmVjb3JkIFN1bW1hcnk8L2gxPgogICAgPHAgY2xhc3M9InN1YnRpdGxlIj5BcHBlbGxhdGUgRG9jdW1lbnQgQW5hbHlzaXMgJmFtcDsgRGlnZXN0PC9wPgogIDwvaGVhZGVyPgoKICA8ZGl2IGNsYXNzPSJ1cGxvYWQtc2VjdGlvbiIgaWQ9InVwbG9hZFNlY3Rpb24iPgogICAgPGRpdiBjbGFzcz0icGljay1hcmVhIiBpZD0icGlja0FyZWEiPgogICAgICA8c3BhbiBjbGFzcz0iZHJvcC1pY29uIj7wn5OEPC9zcGFuPgogICAgICA8aDM+VXBsb2FkIENvdXJ0IG9mIEFwcGVhbHMgUmVjb3JkPC9oMz4KICAgICAgPHA+U2VsZWN0IGEgUERGIHVwIHRvIDkwMCBNQiDigJQgbGFyZ2UgcmVjb3JkcyBhcmUgcHJvY2Vzc2VkIGF1dG9tYXRpY2FsbHk8L3A+CiAgICAgIDxpbnB1dCB0eXBlPSJmaWxlIiBpZD0iZmlsZUlucHV0IiBhY2NlcHQ9Ii5wZGYiIC8+CiAgICAgIDxidXR0b24gY2xhc3M9ImJ0bi1icm93c2UiIG9uY2xpY2s9ImRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdmaWxlSW5wdXQnKS5jbGljaygpIj5Ccm93c2UgZm9yIFBERuKApjwvYnV0dG9uPgogICAgICA8ZGl2IGNsYXNzPSJmaWxlLWluZm8iIGlkPSJmaWxlSW5mbyI+CiAgICAgICAgPHNwYW4+8J+Tjjwvc3Bhbj4KICAgICAgICA8c3BhbiBjbGFzcz0iZm5hbWUiIGlkPSJmaWxlTmFtZSI+PC9zcGFuPgogICAgICAgIDxzcGFuIGNsYXNzPSJmc2l6ZSIgaWQ9ImZpbGVTaXplIj48L3NwYW4+CiAgICAgICAgPGJ1dHRvbiBjbGFzcz0iYnRuLWNsZWFyIiBvbmNsaWNrPSJjbGVhckZpbGUoKSIgdGl0bGU9IlJlbW92ZSI+4pyVPC9idXR0b24+CiAgICAgIDwvZGl2PgogICAgPC9kaXY+CiAgICA8YnV0dG9uIGNsYXNzPSJidG4tYW5hbHl6ZSIgaWQ9ImFuYWx5emVCdG4iIGRpc2FibGVkIG9uY2xpY2s9ImFuYWx5emVEb2N1bWVudCgpIj5BbmFseXplIFJlY29yZDwvYnV0dG9uPgogIDwvZGl2PgoKICA8ZGl2IGNsYXNzPSJwcm9ncmVzcy1zZWN0aW9uIiBpZD0icHJvZ3Jlc3NTZWN0aW9uIj4KICAgIDxkaXYgY2xhc3M9InNwaW5uZXIiPjwvZGl2PgogICAgPHAgY2xhc3M9InByb2dyZXNzLWxhYmVsIiBpZD0icHJvZ3Jlc3NMYWJlbCI+VXBsb2FkaW5nIGRvY3VtZW504oCmPC9wPgogICAgPHAgY2xhc3M9InByb2dyZXNzLXN1YiIgaWQ9InByb2dyZXNzU3ViIj5QbGVhc2Ugd2FpdCDigJQgbGFyZ2UgcmVjb3JkcyBtYXkgdGFrZSBzZXZlcmFsIG1pbnV0ZXM8L3A+CiAgICA8ZGl2IGNsYXNzPSJwcm9ncmVzcy1iYXItd3JhcCI+PGRpdiBjbGFzcz0icHJvZ3Jlc3MtYmFyLWZpbGwiIGlkPSJwcm9ncmVzc0JhckZpbGwiPjwvZGl2PjwvZGl2PgogIDwvZGl2PgoKICA8ZGl2IGNsYXNzPSJlcnJvci1ib3giIGlkPSJlcnJvckJveCI+PC9kaXY+CgogIDxkaXYgaWQ9InJlc3VsdHMiPgogICAgPGRpdiBjbGFzcz0icmVzdWx0cy1oZWFkZXIiPgogICAgICA8aDI+UmVjb3JkIEFuYWx5c2lzPC9oMj4KICAgICAgPGJ1dHRvbiBjbGFzcz0iYnRuLXJlc2V0IiBvbmNsaWNrPSJyZXNldEFwcCgpIj7ihqkgQW5hbHl6ZSBBbm90aGVyPC9idXR0b24+CiAgICA8L2Rpdj4KICAgIDxkaXYgaWQ9InNlY3Rpb25zQ29udGFpbmVyIj48L2Rpdj4KICA8L2Rpdj4KCiAgPGZvb3Rlcj5BcHBlYWwgUmVjb3JkIFN1bW1hcnkgwrcgQUktQXNzaXN0ZWQgTGVnYWwgRG9jdW1lbnQgQW5hbHlzaXMgwrcgTm90IGEgU3Vic3RpdHV0ZSBmb3IgTGVnYWwgQWR2aWNlPC9mb290ZXI+CjwvZGl2PgoKPHNjcmlwdD4KY29uc3QgTUFYX01CID0gOTAwOwpjb25zdCBNQVhfQllURVMgPSBNQVhfTUIgKiAxMDI0ICogMTAyNDsKbGV0IHNlbGVjdGVkRmlsZSA9IG51bGw7Cgpkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZmlsZUlucHV0JykuYWRkRXZlbnRMaXN0ZW5lcignY2hhbmdlJywgZnVuY3Rpb24oZSkgewogIGlmIChlLnRhcmdldC5maWxlcyAmJiBlLnRhcmdldC5maWxlc1swXSkgc2V0RmlsZShlLnRhcmdldC5maWxlc1swXSk7Cn0pOwoKZnVuY3Rpb24gc2V0RmlsZShmaWxlKSB7CiAgaWYgKCFmaWxlLm5hbWUudG9Mb3dlckNhc2UoKS5lbmRzV2l0aCgnLnBkZicpKSB7IHNob3dFcnJvcignUGxlYXNlIHNlbGVjdCBhIFBERiBmaWxlLicpOyByZXR1cm47IH0KICBpZiAoZmlsZS5zaXplID4gTUFYX0JZVEVTKSB7CiAgICBzaG93RXJyb3IoJ1RoaXMgZmlsZSBpcyAnICsgKGZpbGUuc2l6ZS8xMDQ4NTc2KS50b0ZpeGVkKDApICsgJyBNQiwgd2hpY2ggZXhjZWVkcyB0aGUgOTAwIE1CIGxpbWl0LicpOwogICAgcmV0dXJuOwogIH0KICBzZWxlY3RlZEZpbGUgPSBmaWxlOwogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdmaWxlTmFtZScpLnRleHRDb250ZW50ID0gZmlsZS5uYW1lOwogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdmaWxlU2l6ZScpLnRleHRDb250ZW50ID0gZm9ybWF0Qnl0ZXMoZmlsZS5zaXplKTsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZmlsZUluZm8nKS5jbGFzc0xpc3QuYWRkKCd2aXNpYmxlJyk7CiAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3BpY2tBcmVhJykuY2xhc3NMaXN0LmFkZCgnaGFzLWZpbGUnKTsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYW5hbHl6ZUJ0bicpLmRpc2FibGVkID0gZmFsc2U7CiAgaGlkZUVycm9yKCk7Cn0KCmZ1bmN0aW9uIGNsZWFyRmlsZSgpIHsKICBzZWxlY3RlZEZpbGUgPSBudWxsOwogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdmaWxlSW5wdXQnKS52YWx1ZSA9ICcnOwogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdmaWxlSW5mbycpLmNsYXNzTGlzdC5yZW1vdmUoJ3Zpc2libGUnKTsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgncGlja0FyZWEnKS5jbGFzc0xpc3QucmVtb3ZlKCdoYXMtZmlsZScpOwogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdhbmFseXplQnRuJykuZGlzYWJsZWQgPSB0cnVlOwp9CgpmdW5jdGlvbiBmb3JtYXRCeXRlcyhiKSB7CiAgaWYgKGIgPCAxMDI0KSByZXR1cm4gYiArICcgQic7CiAgaWYgKGIgPCAxMDQ4NTc2KSByZXR1cm4gKGIvMTAyNCkudG9GaXhlZCgxKSArICcgS0InOwogIHJldHVybiAoYi8xMDQ4NTc2KS50b0ZpeGVkKDEpICsgJyBNQic7Cn0KCmFzeW5jIGZ1bmN0aW9uIGFuYWx5emVEb2N1bWVudCgpIHsKICBpZiAoIXNlbGVjdGVkRmlsZSkgcmV0dXJuOwoKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndXBsb2FkU2VjdGlvbicpLnN0eWxlLmRpc3BsYXkgPSAnbm9uZSc7CiAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3Jlc3VsdHMnKS5jbGFzc0xpc3QucmVtb3ZlKCd2aXNpYmxlJyk7CiAgaGlkZUVycm9yKCk7CiAgc2hvd1Byb2dyZXNzKCk7CiAgc2V0UHJvZ3Jlc3MoJ1VwbG9hZGluZyBkb2N1bWVudOKApicsICdTZW5kaW5nIHRvIHNlcnZlcuKApicpOwogIGFuaW1hdGVCYXIoMCwgMTUsIDMwMDApOwoKICBjb25zdCBmb3JtRGF0YSA9IG5ldyBGb3JtRGF0YSgpOwogIGZvcm1EYXRhLmFwcGVuZCgnZmlsZScsIHNlbGVjdGVkRmlsZSk7CgogIGxldCByZXNwb25zZTsKICB0cnkgewogICAgcmVzcG9uc2UgPSBhd2FpdCBmZXRjaCgnL2FuYWx5emUnLCB7IG1ldGhvZDogJ1BPU1QnLCBib2R5OiBmb3JtRGF0YSB9KTsKICB9IGNhdGNoIChlKSB7CiAgICByZXR1cm4gZmFpbCgnQ291bGQgbm90IHJlYWNoIHRoZSBzZXJ2ZXI6ICcgKyBlLm1lc3NhZ2UpOwogIH0KCiAgaWYgKHJlc3BvbnNlLm9rKSB7CiAgICBhbmltYXRlQmFyKDE1LCA5MCwgMjAwMCk7CiAgICBzZXRQcm9ncmVzcygnQW5hbHl6aW5nIHRoZSBhcHBlbGxhdGUgcmVjb3JkIHdpdGggQUnigKYnLCAnVGhpcyBtYXkgdGFrZSBzZXZlcmFsIG1pbnV0ZXMgZm9yIGxhcmdlIHJlY29yZHMnKTsKICB9CgogIGxldCBkYXRhOwogIHRyeSB7CiAgICBkYXRhID0gYXdhaXQgcmVzcG9uc2UuanNvbigpOwogIH0gY2F0Y2ggKGUpIHsKICAgIHJldHVybiBmYWlsKCdTZXJ2ZXIgcmV0dXJuZWQgYW4gdW5leHBlY3RlZCByZXNwb25zZS4nKTsKICB9CgogIGlmICghcmVzcG9uc2Uub2sgfHwgZGF0YS5lcnJvcikgewogICAgcmV0dXJuIGZhaWwoZGF0YS5lcnJvciB8fCAnU2VydmVyIGVycm9yICcgKyByZXNwb25zZS5zdGF0dXMpOwogIH0KCiAgYW5pbWF0ZUJhcig5MCwgMTAwLCA1MDApOwogIHNldFRpbWVvdXQoKCkgPT4geyBoaWRlUHJvZ3Jlc3MoKTsgcmVuZGVyUmVzdWx0cyhkYXRhKTsgfSwgNjAwKTsKfQoKLy8gU21vb3RobHkgYW5pbWF0ZSB0aGUgcHJvZ3Jlc3MgYmFyIGJldHdlZW4gdHdvIHZhbHVlcyBvdmVyIGEgZHVyYXRpb24KZnVuY3Rpb24gYW5pbWF0ZUJhcihmcm9tLCB0bywgbXMpIHsKICBjb25zdCBmaWxsID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3Byb2dyZXNzQmFyRmlsbCcpOwogIGNvbnN0IHN0YXJ0ID0gcGVyZm9ybWFuY2Uubm93KCk7CiAgZnVuY3Rpb24gc3RlcChub3cpIHsKICAgIGNvbnN0IHQgPSBNYXRoLm1pbigobm93IC0gc3RhcnQpIC8gbXMsIDEpOwogICAgZmlsbC5zdHlsZS53aWR0aCA9IChmcm9tICsgKHRvIC0gZnJvbSkgKiB0KSArICclJzsKICAgIGlmICh0IDwgMSkgcmVxdWVzdEFuaW1hdGlvbkZyYW1lKHN0ZXApOwogIH0KICByZXF1ZXN0QW5pbWF0aW9uRnJhbWUoc3RlcCk7Cn0KCmZ1bmN0aW9uIHNldFByb2dyZXNzKGxhYmVsLCBzdWIpIHsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgncHJvZ3Jlc3NMYWJlbCcpLnRleHRDb250ZW50ID0gbGFiZWw7CiAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3Byb2dyZXNzU3ViJykudGV4dENvbnRlbnQgPSBzdWI7Cn0KZnVuY3Rpb24gc2hvd1Byb2dyZXNzKCkgeyBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgncHJvZ3Jlc3NTZWN0aW9uJykuY2xhc3NMaXN0LmFkZCgndmlzaWJsZScpOyB9CmZ1bmN0aW9uIGhpZGVQcm9ncmVzcygpIHsgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3Byb2dyZXNzU2VjdGlvbicpLmNsYXNzTGlzdC5yZW1vdmUoJ3Zpc2libGUnKTsgfQpmdW5jdGlvbiBzaG93RXJyb3IobXNnKSB7IGNvbnN0IGIgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZXJyb3JCb3gnKTsgYi50ZXh0Q29udGVudCA9ICfimqAgJyArIG1zZzsgYi5jbGFzc0xpc3QuYWRkKCd2aXNpYmxlJyk7IH0KZnVuY3Rpb24gaGlkZUVycm9yKCkgeyBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZXJyb3JCb3gnKS5jbGFzc0xpc3QucmVtb3ZlKCd2aXNpYmxlJyk7IH0KZnVuY3Rpb24gZmFpbChtc2cpIHsgc2hvd0Vycm9yKG1zZyk7IGhpZGVQcm9ncmVzcygpOyBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndXBsb2FkU2VjdGlvbicpLnN0eWxlLmRpc3BsYXkgPSAnYmxvY2snOyB9CgpmdW5jdGlvbiByZXNldEFwcCgpIHsKICBjbGVhckZpbGUoKTsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndXBsb2FkU2VjdGlvbicpLnN0eWxlLmRpc3BsYXkgPSAnYmxvY2snOwogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdyZXN1bHRzJykuY2xhc3NMaXN0LnJlbW92ZSgndmlzaWJsZScpOwogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdzZWN0aW9uc0NvbnRhaW5lcicpLmlubmVySFRNTCA9ICcnOwogIGhpZGVFcnJvcigpOyBoaWRlUHJvZ3Jlc3MoKTsKfQoKLy8g4pSA4pSAIFJlbmRlciByZXN1bHRzIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgApmdW5jdGlvbiByZW5kZXJSZXN1bHRzKGRhdGEpIHsKICBjb25zdCBjID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3NlY3Rpb25zQ29udGFpbmVyJyk7CiAgYy5pbm5lckhUTUwgPSAnJzsKICBpZiAoZGF0YS5jYXNlVGl0bGUpIHsKICAgIGNvbnN0IGVsID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgncCcpOwogICAgZWwuc3R5bGUuY3NzVGV4dCA9ICdmb250LWZhbWlseToiUGxheWZhaXIgRGlzcGxheSIsc2VyaWY7Zm9udC1zaXplOjEuMXJlbTtjb2xvcjp2YXIoLS1nb2xkKTttYXJnaW4tYm90dG9tOjI0cHg7Zm9udC1zdHlsZTppdGFsaWM7JzsKICAgIGVsLnRleHRDb250ZW50ID0gZGF0YS5jYXNlVGl0bGU7IGMuYXBwZW5kQ2hpbGQoZWwpOwogIH0KICBhZGRTZWN0aW9uKGMsJzEnLCdQbGVhZGluZ3MgRmlsZWQnLCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHJlbmRlclBsZWFkaW5ncyhkYXRhLnBsZWFkaW5nc3x8W10pKTsKICBhZGRTZWN0aW9uKGMsJzInLCdXaXRuZXNzZXMgJiBUZXN0aW1vbnkgKEFmZmlkYXZpdCwgRGVjbGFyYXRpb24sIERlcG9zaXRpb24sIFRyaWFsKScsIHJlbmRlcldpdG5lc3NlcyhkYXRhLndpdG5lc3Nlc3x8W10pKTsKICBhZGRTZWN0aW9uKGMsJzMnLCdEaXNwb3NpdGl2ZSBNb3Rpb25zJywgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHJlbmRlckRpc3Bvc2l0aXZlKGRhdGEuZGlzcG9zaXRpdmVNb3Rpb25zfHxbXSkpOwogIGFkZFNlY3Rpb24oYywnNCcsJ09yZGVycyAmIEp1ZGdtZW50cycsICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgcmVuZGVyT3JkZXJzKGRhdGEub3JkZXJzQW5kSnVkZ21lbnRzfHxbXSkpOwogIGFkZFNlY3Rpb24oYywnNScsJ1RyaWFsJywgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgcmVuZGVyVHJpYWwoZGF0YS50cmlhbHx8e29jY3VycmVkOmZhbHNlfSkpOwogIGFkZFNlY3Rpb24oYywnNicsJ1ByZXRyaWFsIE9yZGVycywgTW90aW9ucyBpbiBMaW1pbmUgJiBQcmV0cmlhbCBSdWxpbmdzJywgICAgICAgICAgICAgcmVuZGVyUHJldHJpYWwoZGF0YS5wcmV0cmlhbE1hdHRlcnN8fFtdKSk7CiAgYWRkU2VjdGlvbihjLCc3JywnVHJpYWwgT2JqZWN0aW9ucycsICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICByZW5kZXJPYmplY3Rpb25zKGRhdGEudHJpYWxPYmplY3Rpb25zfHxbXSkpOwogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdyZXN1bHRzJykuY2xhc3NMaXN0LmFkZCgndmlzaWJsZScpOwp9CgpmdW5jdGlvbiBhZGRTZWN0aW9uKGNvbnRhaW5lciwgbnVtLCB0aXRsZSwgYm9keUhUTUwpIHsKICBjb25zdCBjYXJkID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnZGl2Jyk7CiAgY2FyZC5jbGFzc05hbWUgPSAnc2VjdGlvbi1jYXJkJzsKICBjYXJkLmlubmVySFRNTCA9IGA8ZGl2IGNsYXNzPSJzZWN0aW9uLWhlYWRlciIgb25jbGljaz0idG9nZ2xlU2VjdGlvbih0aGlzLnBhcmVudEVsZW1lbnQpIj48ZGl2IGNsYXNzPSJzZWN0aW9uLW51bSI+JHtudW19PC9kaXY+PGRpdiBjbGFzcz0ic2VjdGlvbi10aXRsZSI+JHt0aXRsZX08L2Rpdj48ZGl2IGNsYXNzPSJzZWN0aW9uLXRvZ2dsZSI+4pa+PC9kaXY+PC9kaXY+PGRpdiBjbGFzcz0ic2VjdGlvbi1ib2R5Ij4ke2JvZHlIVE1MfTwvZGl2PmA7CiAgY29udGFpbmVyLmFwcGVuZENoaWxkKGNhcmQpOwp9CmZ1bmN0aW9uIHRvZ2dsZVNlY3Rpb24oY2FyZCkgeyBjYXJkLmNsYXNzTGlzdC50b2dnbGUoJ2NvbGxhcHNlZCcpOyB9CmZ1bmN0aW9uIGR0KGQpIHsgaWYgKCFkfHxkPT09J3Vua25vd24nKSByZXR1cm4gJyc7IHJldHVybiBgPHNwYW4gY2xhc3M9ImRhdGUtdGFnIj4ke2VzY0h0bWwoZCl9PC9zcGFuPmA7IH0KZnVuY3Rpb24gZXNjSHRtbChzKSB7IGlmICghcykgcmV0dXJuICcnOyByZXR1cm4gU3RyaW5nKHMpLnJlcGxhY2UoLyYvZywnJmFtcDsnKS5yZXBsYWNlKC88L2csJyZsdDsnKS5yZXBsYWNlKC8+L2csJyZndDsnKTsgfQoKZnVuY3Rpb24gcmVuZGVyUGxlYWRpbmdzKGl0ZW1zKSB7CiAgaWYgKCFpdGVtcy5sZW5ndGgpIHJldHVybiAnPHA+PGVtPk5vIHBsZWFkaW5ncyBpZGVudGlmaWVkIGluIHRoZSByZWNvcmQuPC9lbT48L3A+JzsKICByZXR1cm4gaXRlbXMubWFwKHA9PmA8ZGl2IGNsYXNzPSJkb2MtZW50cnkiPiR7ZHQocC5kYXRlKX08c3Ryb25nPiR7ZXNjSHRtbChwLnRpdGxlKX08L3N0cm9uZz4ke3AudHlwZT9gIDxzcGFuIHN0eWxlPSJjb2xvcjp2YXIoLS10ZXh0LWxpZ2h0KTtmb250LXNpemU6MC44NXJlbTsiPlske2VzY0h0bWwocC50eXBlKX1dPC9zcGFuPmA6Jyd9JHtwLnN1bW1hcnk/YDxwIHN0eWxlPSJtYXJnaW4tdG9wOjZweDsiPiR7ZXNjSHRtbChwLnN1bW1hcnkpfTwvcD5gOicnfTwvZGl2PmApLmpvaW4oJycpOwp9CmZ1bmN0aW9uIHJlbmRlcldpdG5lc3NlcyhpdGVtcykgewogIGlmICghaXRlbXMubGVuZ3RoKSByZXR1cm4gJzxwPjxlbT5ObyB3aXRuZXNzIHRlc3RpbW9ueSBpZGVudGlmaWVkIGluIHRoZSByZWNvcmQuPC9lbT48L3A+JzsKICByZXR1cm4gaXRlbXMubWFwKHc9PmA8ZGl2IGNsYXNzPSJkb2MtZW50cnkiPjxzdHJvbmcgc3R5bGU9ImNvbG9yOnZhcigtLWdvbGQtbGlnaHQpOyI+JHtlc2NIdG1sKHcubmFtZSl9PC9zdHJvbmc+JHt3LnR5cGU/YCA8c3BhbiBzdHlsZT0iY29sb3I6dmFyKC0tdGV4dC1saWdodCk7Zm9udC1zaXplOjAuODVyZW07Ij5bJHtlc2NIdG1sKHcudHlwZSl9XTwvc3Bhbj5gOicnfSR7ZHQody5kYXRlKX0ke3cua2V5VGVzdGltb255JiZ3LmtleVRlc3RpbW9ueS5sZW5ndGg/YDx1bCBzdHlsZT0ibWFyZ2luLXRvcDo4cHg7Ij4ke3cua2V5VGVzdGltb255Lm1hcCh0PT5gPGxpPiR7ZXNjSHRtbCh0KX08L2xpPmApLmpvaW4oJycpfTwvdWw+YDonJ308L2Rpdj5gKS5qb2luKCcnKTsKfQpmdW5jdGlvbiByZW5kZXJEaXNwb3NpdGl2ZShpdGVtcykgewogIGlmICghaXRlbXMubGVuZ3RoKSByZXR1cm4gJzxwPjxlbT5ObyBkaXNwb3NpdGl2ZSBtb3Rpb25zIGlkZW50aWZpZWQgaW4gdGhlIHJlY29yZC48L2VtPjwvcD4nOwogIHJldHVybiBpdGVtcy5tYXAobT0+YDxkaXYgY2xhc3M9ImRvYy1lbnRyeSI+JHtkdChtLmRhdGUpfTxzdHJvbmc+JHtlc2NIdG1sKG0udGl0bGUpfTwvc3Ryb25nPiR7bS50eXBlP2AgPHNwYW4gc3R5bGU9ImNvbG9yOnZhcigtLXRleHQtbGlnaHQpO2ZvbnQtc2l6ZTowLjg1cmVtOyI+WyR7ZXNjSHRtbChtLnR5cGUpfV08L3NwYW4+YDonJ30ke20uZmlsZWRCeT9gPGRpdiBzdHlsZT0iZm9udC1zaXplOjAuODhyZW07Y29sb3I6dmFyKC0tdGV4dC1saWdodCk7bWFyZ2luLXRvcDo0cHg7Ij5GaWxlZCBieTogJHtlc2NIdG1sKG0uZmlsZWRCeSl9PC9kaXY+YDonJ30ke20ubWFpbkFyZ3VtZW50cyYmbS5tYWluQXJndW1lbnRzLmxlbmd0aD9gPGg0Pk1haW4gQXJndW1lbnRzPC9oND48dWw+JHttLm1haW5Bcmd1bWVudHMubWFwKGE9PmA8bGk+JHtlc2NIdG1sKGEpfTwvbGk+YCkuam9pbignJyl9PC91bD5gOicnfSR7bS5jb3VydFJ1bGluZz9gPGRpdiBzdHlsZT0ibWFyZ2luLXRvcDo4cHg7Ij48c3Ryb25nIHN0eWxlPSJjb2xvcjp2YXIoLS1nb2xkKTsiPkNvdXJ0IFJ1bGluZzwvc3Ryb25nPiAke2R0KG0ucnVsaW5nRGF0ZSl9PGJyPiR7ZXNjSHRtbChtLmNvdXJ0UnVsaW5nKX08L2Rpdj5gOicnfTwvZGl2PmApLmpvaW4oJycpOwp9CmZ1bmN0aW9uIHJlbmRlck9yZGVycyhpdGVtcykgewogIGlmICghaXRlbXMubGVuZ3RoKSByZXR1cm4gJzxwPjxlbT5ObyBvcmRlcnMgb3IganVkZ21lbnRzIGlkZW50aWZpZWQgaW4gdGhlIHJlY29yZC48L2VtPjwvcD4nOwogIHJldHVybiBpdGVtcy5tYXAobz0+YDxkaXYgY2xhc3M9ImRvYy1lbnRyeSI+JHtkdChvLmRhdGUpfTxzdHJvbmc+JHtlc2NIdG1sKG8udGl0bGUpfTwvc3Ryb25nPiR7by50eXBlP2AgPHNwYW4gc3R5bGU9ImNvbG9yOnZhcigtLXRleHQtbGlnaHQpO2ZvbnQtc2l6ZTowLjg1cmVtOyI+WyR7ZXNjSHRtbChvLnR5cGUpfV08L3NwYW4+YDonJ30ke28uc3VtbWFyeT9gPHAgc3R5bGU9Im1hcmdpbi10b3A6NnB4OyI+JHtlc2NIdG1sKG8uc3VtbWFyeSl9PC9wPmA6Jyd9PC9kaXY+YCkuam9pbignJyk7Cn0KZnVuY3Rpb24gcmVuZGVyVHJpYWwodHJpYWwpIHsKICBpZiAoIXRyaWFsLm9jY3VycmVkKSByZXR1cm4gJzxwPjxlbT5ObyB0cmlhbCBpcyByZWZsZWN0ZWQgaW4gdGhpcyByZWNvcmQuPC9lbT48L3A+JzsKICBsZXQgaHRtbD0nJzsKICBpZiAodHJpYWwuc3RhcnREYXRlfHx0cmlhbC5lbmREYXRlKSBodG1sKz1gPHA+PHN0cm9uZz5UcmlhbCBEYXRlczo8L3N0cm9uZz4gJHtlc2NIdG1sKHRyaWFsLnN0YXJ0RGF0ZXx8JycpfSR7dHJpYWwuZW5kRGF0ZSYmdHJpYWwuZW5kRGF0ZSE9PXRyaWFsLnN0YXJ0RGF0ZT8nIOKAkyAnK2VzY0h0bWwodHJpYWwuZW5kRGF0ZSk6Jyd9PC9wPmA7CiAgaWYgKHRyaWFsLnN1bW1hcnkpIGh0bWwrPWA8cD4ke2VzY0h0bWwodHJpYWwuc3VtbWFyeSl9PC9wPmA7CiAgKHRyaWFsLmRheXN8fFtdKS5mb3JFYWNoKGQ9PnsKICAgIGh0bWwrPWA8aDM+RGF5ICR7ZC5kYXlOdW1iZXJ9JHtkLmRhdGU/JyDigJQgJytlc2NIdG1sKGQuZGF0ZSk6Jyd9PC9oMz5gOwogICAgaWYoZC5kZXNjcmlwdGlvbilodG1sKz1gPHA+JHtlc2NIdG1sKGQuZGVzY3JpcHRpb24pfTwvcD5gOwogICAgaWYoZC53aXRuZXNzZXMmJmQud2l0bmVzc2VzLmxlbmd0aClodG1sKz1gPHA+PHN0cm9uZz5XaXRuZXNzZXM6PC9zdHJvbmc+ICR7ZC53aXRuZXNzZXMubWFwKGVzY0h0bWwpLmpvaW4oJywgJyl9PC9wPmA7CiAgICBpZihkLnNpZ25pZmljYW50RXZlbnRzJiZkLnNpZ25pZmljYW50RXZlbnRzLmxlbmd0aClodG1sKz1gPHVsPiR7ZC5zaWduaWZpY2FudEV2ZW50cy5tYXAoZT0+YDxsaT4ke2VzY0h0bWwoZSl9PC9saT5gKS5qb2luKCcnKX08L3VsPmA7CiAgfSk7CiAgaWYodHJpYWwuZXhoaWJpdHMmJnRyaWFsLmV4aGliaXRzLmxlbmd0aCl7CiAgICBodG1sKz1gPGgzPkV4aGliaXRzPC9oMz5gOwogICAgaHRtbCs9dHJpYWwuZXhoaWJpdHMubWFwKGV4PT5gPGRpdiBjbGFzcz0iZG9jLWVudHJ5Ij48c3Ryb25nPkV4aGliaXQgJHtlc2NIdG1sKGV4LmlkKX08L3N0cm9uZz4gJHtkdChleC5kYXRlKX0ke2V4LmFkbWl0dGVkIT09dW5kZWZpbmVkPyhleC5hZG1pdHRlZD8nPHNwYW4gY2xhc3M9InRhZy1hZG1pdHRlZCI+QURNSVRURUQ8L3NwYW4+JzonPHNwYW4gY2xhc3M9InRhZy1kZW5pZWQiPk5PVCBBRE1JVFRFRDwvc3Bhbj4nKTonJ30ke2V4Lm9mZmVyZWRCeT9gIDxzcGFuIHN0eWxlPSJmb250LXNpemU6MC44NXJlbTtjb2xvcjp2YXIoLS10ZXh0LWxpZ2h0KTsiPk9mZmVyZWQgYnk6ICR7ZXNjSHRtbChleC5vZmZlcmVkQnkpfTwvc3Bhbj5gOicnfTxkaXYgc3R5bGU9Im1hcmdpbi10b3A6NHB4OyI+JHtlc2NIdG1sKGV4LmRlc2NyaXB0aW9uKX08L2Rpdj4ke2V4LnJlYXNvbj9gPGRpdiBzdHlsZT0iZm9udC1zaXplOjAuODhyZW07Y29sb3I6dmFyKC0tdGV4dC1saWdodCk7Ij4ke2VzY0h0bWwoZXgucmVhc29uKX08L2Rpdj5gOicnfTwvZGl2PmApLmpvaW4oJycpOwogIH0KICByZXR1cm4gaHRtbHx8JzxwPjxlbT5UcmlhbCBvY2N1cnJlZCBidXQgZGV0YWlscyB3ZXJlIG5vdCBleHRyYWN0ZWQuPC9lbT48L3A+JzsKfQpmdW5jdGlvbiByZW5kZXJQcmV0cmlhbChpdGVtcykgewogIGlmICghaXRlbXMubGVuZ3RoKSByZXR1cm4gJzxwPjxlbT5ObyBwcmV0cmlhbCBtb3Rpb25zIG9yIG9yZGVycyBpZGVudGlmaWVkIGluIHRoZSByZWNvcmQuPC9lbT48L3A+JzsKICByZXR1cm4gaXRlbXMubWFwKG09PmA8ZGl2IGNsYXNzPSJkb2MtZW50cnkiPiR7ZHQobS5kYXRlKX08c3Ryb25nPiR7ZXNjSHRtbChtLnRpdGxlKX08L3N0cm9uZz4ke20udHlwZT9gIDxzcGFuIHN0eWxlPSJjb2xvcjp2YXIoLS10ZXh0LWxpZ2h0KTtmb250LXNpemU6MC44NXJlbTsiPlske2VzY0h0bWwobS50eXBlKX1dPC9zcGFuPmA6Jyd9JHttLnN1bW1hcnk/YDxwIHN0eWxlPSJtYXJnaW4tdG9wOjZweDsiPiR7ZXNjSHRtbChtLnN1bW1hcnkpfTwvcD5gOicnfSR7bS5ydWxpbmc/YDxwPjxzdHJvbmcgc3R5bGU9ImNvbG9yOnZhcigtLWdvbGQpOyI+UnVsaW5nOjwvc3Ryb25nPiAke2VzY0h0bWwobS5ydWxpbmcpfTwvcD5gOicnfTwvZGl2PmApLmpvaW4oJycpOwp9CmZ1bmN0aW9uIHJlbmRlck9iamVjdGlvbnMoaXRlbXMpIHsKICBpZiAoIWl0ZW1zLmxlbmd0aCkgcmV0dXJuICc8cD48ZW0+Tm8gdHJpYWwgb2JqZWN0aW9ucyBpZGVudGlmaWVkIGluIHRoZSByZWNvcmQuPC9lbT48L3A+JzsKICByZXR1cm4gaXRlbXMubWFwKG89PmA8ZGl2IGNsYXNzPSJkb2MtZW50cnkiPiR7ZHQoby5kYXRlKX0ke28uc3VzdGFpbmVkIT09dW5kZWZpbmVkPyhvLnN1c3RhaW5lZD8nPHNwYW4gY2xhc3M9InRhZy1hZG1pdHRlZCI+U1VTVEFJTkVEPC9zcGFuPic6JzxzcGFuIGNsYXNzPSJ0YWctZGVuaWVkIj5PVkVSUlVMRUQ8L3NwYW4+Jyk6Jyd9JHtvLm9iamVjdGluZ1BhcnR5P2AgPHN0cm9uZz4ke2VzY0h0bWwoby5vYmplY3RpbmdQYXJ0eSl9PC9zdHJvbmc+YDonJ30ke28uYmFzaXM/YCA8c3BhbiBzdHlsZT0iY29sb3I6dmFyKC0tdGV4dC1saWdodCk7Zm9udC1zaXplOjAuODhyZW07Ij5CYXNpczogJHtlc2NIdG1sKG8uYmFzaXMpfTwvc3Bhbj5gOicnfSR7by5ldmlkZW5jZU9yVGVzdGltb255P2A8cCBzdHlsZT0ibWFyZ2luLXRvcDo2cHg7Ij4ke2VzY0h0bWwoby5ldmlkZW5jZU9yVGVzdGltb255KX08L3A+YDonJ30ke28uY291cnRSdWxpbmc/YDxwPjxzdHJvbmcgc3R5bGU9ImNvbG9yOnZhcigtLWdvbGQpOyI+UnVsaW5nOjwvc3Ryb25nPiAke2VzY0h0bWwoby5jb3VydFJ1bGluZyl9PC9wPmA6Jyd9PC9kaXY+YCkuam9pbignJyk7Cn0KPC9zY3JpcHQ+CjwvYm9keT4KPC9odG1sPgo="
INDEX_HTML = base64.b64decode(_HTML_B64).decode("utf-8")
 
SYSTEM_PROMPT = """You are an expert appellate attorney and legal analyst specializing in reviewing and summarizing court of appeals records. Your task is to thoroughly analyze the uploaded court record and produce a structured, comprehensive summary.
 
Return ONLY valid JSON — no markdown fences, no preamble, nothing else.
 
The JSON must have exactly these keys:
{
  "caseTitle": "string — case name/number if identifiable",
  "pleadings": [...],
  "witnesses": [...],
  "dispositiveMotions": [...],
  "ordersAndJudgments": [...],
  "trial": { ... },
  "pretrialMatters": [...],
  "trialObjections": [...]
}
 
For each array item, include a "date" field (string, e.g. "March 5, 2021" or "unknown") and a "title" field.
 
pleadings: each item: { date, title, type (e.g. "Petition","Answer","Affirmative Defense","Third-Party Petition", etc.), summary }
witnesses: each item: { name, date, type ("Affidavit"|"Declaration"|"Deposition"|"Trial Testimony"), keyTestimony (array of strings) }
dispositiveMotions: each item: { date, title, type ("Motion to Dismiss"|"Motion for Summary Judgment"|"Plea to the Jurisdiction"|"Motion for Directed Verdict"|other), filedBy, mainArguments (array of strings), courtRuling, rulingDate }
ordersAndJudgments: each item: { date, title, type ("Interlocutory Order"|"Final Judgment"|"Partial Summary Judgment"|"Order on Motion"|other), summary }
trial: { occurred: boolean, startDate: string, endDate: string, days: [ { dayNumber, date, description, witnesses: [string], significantEvents: [string] } ], exhibits: [ { id, description, offeredBy, date, admitted: boolean, reason } ], summary: string }
pretrialMatters: each item: { date, title, type ("Motion in Limine"|"Pretrial Order"|"Scheduling Order"|"Pretrial Conference"|other), summary, ruling }
trialObjections: each item: { date, objectingParty, basis, evidenceOrTestimony, courtRuling, sustained: boolean }
 
Be exhaustive. If a section has no relevant documents return an empty array (or for trial, occurred: false). For dates, use the format found in the document."""
 
MERGE_PROMPT = """You are an expert appellate attorney. Merge all the partial summaries below into one comprehensive, deduplicated summary.
 
Return ONLY valid JSON with exactly these keys: caseTitle, pleadings, witnesses, dispositiveMotions, ordersAndJudgments, trial, pretrialMatters, trialObjections.
 
For the trial object: if any section shows a trial occurred, set occurred: true and merge the days, exhibits, and summary from all sections.
 
Partial summaries to merge:
"""
 
def make_client():
    """Create anthropic client — compatible with all recent library versions."""
    import anthropic
    try:
        # Newer versions (>=0.40)
        return anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    except TypeError:
        # Fallback: set via environment variable
        os.environ["ANTHROPIC_API_KEY"] = ANTHROPIC_API_KEY
        return anthropic.Anthropic()
 
@app.route("/")
def index():
    return Response(INDEX_HTML, mimetype="text/html")
 
@app.route("/health")
def health():
    return jsonify({
        "status": "ok",
        "html_chars": len(INDEX_HTML),
        "api_key_set": bool(ANTHROPIC_API_KEY),
        "python": sys.version,
    })
 
@app.route("/versions")
def versions():
    """Show installed package versions — useful for debugging."""
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "list", "--format=json"],
            capture_output=True, text=True, timeout=10
        )
        pkgs = json.loads(result.stdout)
        wanted = {p["name"].lower(): p["version"] for p in pkgs
                  if p["name"].lower() in ("anthropic","httpx","flask","pymupdf","fitz")}
        return jsonify(wanted)
    except Exception as e:
        return jsonify({"error": str(e)})
 
@app.route("/analyze", methods=["POST"])
def analyze():
    try:
        return _analyze()
    except Exception as e:
        print("UNHANDLED ERROR:\n", traceback.format_exc())
        return jsonify({"error": f"Unexpected server error: {str(e)}"}), 500
 
def _analyze():
    if not ANTHROPIC_API_KEY:
        return jsonify({"error": "Server is missing ANTHROPIC_API_KEY. Add it in Render dashboard under Environment."}), 500
 
    if "file" not in request.files:
        return jsonify({"error": "No file received."}), 400
 
    f = request.files["file"]
    fname = f.filename or ""
    if not fname.lower().endswith(".pdf"):
        return jsonify({"error": "Please upload a PDF file."}), 400
 
    try:
        pdf_bytes = f.read()
    except Exception as e:
        return jsonify({"error": f"Failed to read file: {str(e)}"}), 400
 
    if not pdf_bytes:
        return jsonify({"error": "The uploaded file is empty."}), 400
 
    mb = len(pdf_bytes) / 1048576
    print(f"File: {fname}  {mb:.1f} MB")
 
    if len(pdf_bytes) > MAX_FILE_BYTES:
        return jsonify({"error": f"File is {mb:.0f} MB. Maximum is 900 MB."}), 400
 
    import fitz
    try:
        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    except Exception as e:
        return jsonify({"error": f"Could not open PDF (corrupted or password-protected): {str(e)}"}), 400
 
    total_pages = len(doc)
    print(f"Pages: {total_pages}")
 
    try:
        client = make_client()
    except Exception as e:
        return jsonify({"error": f"Could not initialise AI client: {str(e)}"}), 500
 
    # Small PDF: send as base64
    if total_pages <= MAX_PAGES_PER_CHUNK and len(pdf_bytes) <= 32 * 1024 * 1024:
        doc.close()
        print("Strategy: direct base64")
        try:
            return jsonify(analyze_pdf_bytes(client, pdf_bytes))
        except Exception as e:
            print("Direct error:\n", traceback.format_exc())
            return jsonify({"error": f"Analysis failed: {str(e)}"}), 500
 
    # Large PDF: extract text, chunk, analyze, merge
    n = math.ceil(total_pages / MAX_PAGES_PER_CHUNK)
    print(f"Strategy: chunked text ({n} chunks)")
    try:
        partials = analyze_in_chunks(client, doc, total_pages)
        doc.close()
    except Exception as e:
        doc.close()
        print("Chunk error:\n", traceback.format_exc())
        return jsonify({"error": f"Analysis failed during text extraction: {str(e)}"}), 500
 
    if not partials:
        return jsonify({"error": "No readable text found. The PDF may be a scanned image without OCR text."}), 400
 
    try:
        result = partials[0] if len(partials) == 1 else merge_results(client, partials)
        return jsonify(result)
    except Exception as e:
        print("Merge error:\n", traceback.format_exc())
        return jsonify({"error": f"Analysis failed during merge: {str(e)}"}), 500
 
 
def analyze_pdf_bytes(client, pdf_bytes):
    b64 = base64.b64encode(pdf_bytes).decode("utf-8")
    r = client.messages.create(
        model="claude-sonnet-4-20250514", max_tokens=8000, system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": [
            {"type": "document", "source": {"type": "base64", "media_type": "application/pdf", "data": b64}},
            {"type": "text", "text": "Analyze this appellate court record and return the structured JSON summary."}
        ]}]
    )
    return parse_json(r.content[0].text)
 
 
def analyze_in_chunks(client, doc, total_pages):
    results = []
    n = math.ceil(total_pages / MAX_PAGES_PER_CHUNK)
    for i in range(n):
        start = i * MAX_PAGES_PER_CHUNK
        end = min(start + MAX_PAGES_PER_CHUNK, total_pages)
        label = f"pages {start+1}-{end} of {total_pages}"
        print(f"  Chunk {i+1}/{n}: {label}")
        parts = []
        for p in range(start, end):
            t = doc[p].get_text("text")
            if t.strip():
                parts.append(f"[Page {p+1}]\n{t}")
        text = "\n\n".join(parts)
        if not text.strip():
            print(f"    No text, skipping")
            continue
        try:
            r = client.messages.create(
                model="claude-sonnet-4-20250514", max_tokens=8000, system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": f"Analyze this section ({label}) and return the structured JSON summary.\n\n{text}"}]
            )
            results.append(parse_json(r.content[0].text))
            print(f"    OK")
        except Exception as e:
            print(f"    Error: {e}")
    return results
 
 
def merge_results(client, partials):
    combined = json.dumps(partials, indent=2)
    print(f"Merging {len(partials)} partials")
    r = client.messages.create(
        model="claude-sonnet-4-20250514", max_tokens=8000,
        system=MERGE_PROMPT + combined,
        messages=[{"role": "user", "content": "Merge these partial summaries into one comprehensive JSON summary."}]
    )
    return parse_json(r.content[0].text)
 
 
def parse_json(raw):
    clean = raw.strip()
    if "```" in clean:
        for part in clean.split("```"):
            part = part.strip()
            if part.startswith("json"):
                part = part[4:].strip()
            try:
                return json.loads(part)
            except Exception:
                continue
    return json.loads(clean)
 
 
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
